# fmp_data/mcp/tools_manifest.py
"""
Declarative list of MCP tools to expose.

Each tool is referenced by its semantic key as discovered by the MCP discovery system.
Tools are organized by client module for clarity.

To customize the available tools, modify the DEFAULT_TOOLS list or set the
FMP_MCP_MANIFEST environment variable to point to a custom manifest file.
"""

DEFAULT_TOOLS: list[str] = [
    # Alternative (21 tools) - Crypto, Forex, and Commodities
    "alternative.commodities_list",
    "alternative.commodities_quotes",
    "alternative.commodity_historical",
    "alternative.commodity_historical_light",
    "alternative.commodity_intraday",
    "alternative.commodity_quote",
    "alternative.commodity_quote_short",
    "alternative.crypto_historical",
    "alternative.crypto_historical_light",
    "alternative.crypto_intraday",
    "alternative.crypto_list",
    "alternative.crypto_quote",
    "alternative.crypto_quote_short",
    "alternative.crypto_quotes",
    "alternative.forex_historical",
    "alternative.forex_historical_light",
    "alternative.forex_intraday",
    "alternative.forex_list",
    "alternative.forex_quote",
    "alternative.forex_quote_short",
    "alternative.forex_quotes",
    # Batch (7 tools) - Bulk Quote Data
    "batch.full_exchange_quotes",
    "batch.full_etf_quotes",
    "batch.full_mutualfund_quotes",
    "batch.full_crypto_quotes",
    "batch.full_commodities_quotes",
    "batch.full_forex_quotes",
    "batch.full_index_quotes",
    # Company (31 tools) - Company Information and Quotes
    "company.analyst_estimates",
    "company.analyst_recommendations",
    "company.company_notes",
    "company.core_information",
    "company.employee_count",
    "company.executive_compensation",
    "company.executives",
    "company.aftermarket_quote",
    "company.aftermarket_trade",
    "company.geographic_revenue_segmentation",
    "company.historical_market_cap",
    "company.historical_price",
    "company.historical_prices",
    "company.historical_share_float",
    "company.intraday_price",
    "company.intraday_prices",
    "company.key_executives",
    "company.market_cap",
    "company.price_target",
    "company.price_target_consensus",
    "company.price_target_summary",
    "company.product_revenue_segmentation",
    "company.profile",
    "company.quote",
    "company.share_float",
    "company.simple_quote",
    "company.stock_price_change",
    "company.symbol_changes",
    "company.upgrades_downgrades",
    "company.upgrades_downgrades_consensus",
    # Economics (4 tools) - Economic Indicators
    "economics.economic_calendar",
    "economics.economic_indicators",
    "economics.market_risk_premium",
    "economics.commitment_of_traders_report",
    "economics.commitment_of_traders_analysis",
    "economics.commitment_of_traders_list",
    "economics.treasury_rates",
    # Fundamental (14 tools) - Financial Statements and Valuation
    "fundamental.balance_sheet",
    "fundamental.cash_flow",
    "fundamental.custom_discounted_cash_flow",
    "fundamental.custom_levered_dcf",
    "fundamental.discounted_cash_flow",
    "fundamental.financial_ratios",
    "fundamental.full_financial_statement",
    "fundamental.historical_rating",
    "fundamental.income_statement",
    "fundamental.key_metrics",
    "fundamental.levered_dcf",
    "fundamental.latest_financial_statements",
    "fundamental.owner_earnings",
    # Institutional (13 tools) - Institutional and Insider Data
    "institutional.asset_allocation",
    "institutional.beneficial_ownership",
    "institutional.fail_to_deliver",
    "institutional.form_13f",
    "institutional.form_13f_dates",
    "institutional.insider_roster",
    "institutional.insider_statistics",
    "institutional.insider_trades",
    "institutional.institutional_holdings",
    "institutional.transaction_types",
    # Intelligence (34 tools) - News, Sentiment, and Market Events
    "intelligence.crowdfunding_by_cik",
    "intelligence.crowdfunding_rss",
    "intelligence.crypto_news",
    "intelligence.crypto_symbol_news",
    "intelligence.dividends_calendar",
    "intelligence.earnings_calendar",
    "intelligence.earnings_confirmed",
    "intelligence.earnings_surprises",
    "intelligence.equity_offering_by_cik",
    "intelligence.equity_offering_rss",
    "intelligence.esg_benchmark",
    "intelligence.esg_data",
    "intelligence.esg_ratings",
    "intelligence.fmp_articles",
    "intelligence.forex_news",
    "intelligence.forex_symbol_news",
    "intelligence.general_news",
    "intelligence.historical_earnings",
    "intelligence.historical_social_sentiment",
    "intelligence.house_disclosure",
    "intelligence.house_latest",
    "intelligence.house_trades_by_name",
    "intelligence.ipo_calendar",
    "intelligence.press_releases",
    "intelligence.press_releases_by_symbol",
    "intelligence.senate_trading",
    "intelligence.senate_trading_rss",
    "intelligence.senate_latest",
    "intelligence.senate_trades_by_name",
    "intelligence.social_sentiment_changes",
    "intelligence.stock_news",
    "intelligence.stock_news_sentiments",
    "intelligence.stock_splits_calendar",
    "intelligence.trending_social_sentiment",
    # Investment (11 tools) - ETFs and Mutual Funds
    "investment.etf_country_weightings",
    "investment.etf_exposure",
    "investment.etf_holder",
    "investment.etf_holding_dates",
    "investment.etf_holdings",
    "investment.etf_info",
    "investment.etf_sector_weightings",
    "investment.fund_disclosure",
    "investment.fund_disclosure_holders_latest",
    "investment.fund_disclosure_holders_search",
    "investment.mutual_fund_by_name",
    "investment.mutual_fund_dates",
    "investment.mutual_fund_holder",
    "investment.mutual_fund_holdings",
    # Index (9 tools) - Market Index Data
    "index.indexes_list",
    "index.index_quote",
    "index.index_quote_short",
    "index.all_index_quotes",
    "index.index_historical_eod_full",
    "index.index_historical_eod_light",
    "index.index_intraday_1min",
    "index.index_intraday_5min",
    "index.index_intraday_1hour",
    # Market (17 tools) - Market Data and Search
    "market.all_shares_float",
    "market.all_exchange_market_hours",
    "market.available_indexes",
    "market.company_symbols_list",
    "market.etf_list",
    "market.gainers",
    "market.historical_industry_pe",
    "market.historical_industry_performance",
    "market.historical_sector_pe",
    "market.historical_sector_performance",
    "market.industry_pe_snapshot",
    "market.industry_performance_snapshot",
    "market.is_market_open",
    "market.holidays_by_exchange",
    "market.losers",
    "market.market_hours",
    "market.most_active",
    "market.pre_post_market",
    "market.search_by_cik",
    "market.search_by_cusip",
    "market.search_by_isin",
    "market.sector_pe_snapshot",
    "market.sector_performance",
    "market.stock_list",
    "market.symbol_changes_list",
    # Technical (9 tools) - Technical Indicators
    "technical.adx",
    "technical.dema",
    "technical.ema",
    "technical.rsi",
    "technical.sma",
    "technical.standard_deviation",
    "technical.tema",
    "technical.williams",
    "technical.wma",
]

# Minimal set for quick testing
MINIMAL_TOOLS: list[str] = [
    "company.profile",
    "company.quote",
    "alternative.crypto_quote",
]

# Extended set for comprehensive coverage
EXTENDED_TOOLS: list[str] = [
    *DEFAULT_TOOLS,
    # Additional company data
    "company.price_target_summary",
    "company.share_float",
    "company.company_notes",
    # More market data
    "market.available_indexes",
    "market.search",
    # Institutional data
    "institutional.institutional_holders",
    "institutional.insider_trades",
    # Investment products
    "investment.etf_info",
    "investment.etf_holdings",
    # More technical indicators
    "technical.ema",
    "technical.williams",
    "technical.adx",
]
